---
default: &default
  send_activation_mail: false
  trust_basic_auth: false
  disable_registration: false
  can_change_password: true
  can_disable_account: true
  can_use_yubikey: true
  create_auth_ondemand:
    enabled: false
    default_mail_domain: hovedprosjekt.hioa
    random_password: true
  name: Hovedprosjekt Gruppe 20
  host: pc29-75.iu.hio.no
  email: noreply@example.com
  use_ssl: false
  email_as_login: false
  session:
    key: openidserver_session_id
    secret: weeeeeeplacethiswithyourowntopsecretsessionsecretsothatnoonewillknowit
  mailer:
    address: localhost
    domain: example.com
    from: noreply@example.com
  yubico:
    id: 99
    api_key: youryubicoapikey
  attribute_mappings:
    nickname:
      - nickname
      - http://openid.net/schema/namePerson/friendly
    email:
      - email
      - http://openid.net/schema/contact/email
    fullname:
      - fullname
      - http://openid.net/schema/namePerson
    postcode:
      - postcode
      - http://openid.net/schema/contact/postalCode/home
    country:
      - country
      - http://openid.net/schema/contact/country/home
    language:
      - language
      - http://openid.net/schema/pref/language
    timezone:
      - timezone
      - http://openid.net/schema/pref/timezone
    gender:
      - gender
      - http://openid.net/schema/person/gender
    date_of_birth:
      - dob
      - http://openid.net/schema/birthDate
    dob_day:
      - dob_day
      - http://openid.net/schema/birthDate/birthday
    dob_month:
      - dob_month
      - http://openid.net/schema/birthDate/birthMonth
    dob_year:
      - dob_year
      - http://openid.net/schema/birthhttp://openid.net/schema/person/genderDate/birthYear
    address:
      - http://openid.net/schema/contact/postalAddress/home
    address_additional:
      - http://openid.net/schema/contact/postalAddressAdditional/home
    city:
      - http://openid.net/schema/contact/city/home
    state:
      - http://openid.net/schema/contact/state/home
    company_name:
      - http://openid.net/schema/company/name
    job_title:
      - http://openid.net/schema/company/title
    address_business:
      - http://openid.net/schema/contact/postalAddress/business
    address_additional_business:
      - http://openid.net/schema/contact/postalAddressAdditional/business
    postcode_business:
      - http://openid.net/schema/contact/postalCode/business
    city_business:
      - http://openid.net/schema/contact/city/business
    state_business:
      - http://openid.net/schema/contact/state/business
    country_business:
      - http://openid.net/schema/contact/country/business
    phone_home:
      - http://openid.net/schema/contact/phone/home
    phone_mobile:
      - http://openid.net/schema/contact/phone/cell
    phone_work:
      - http://openid.net/schema/contact/phone/business
    phone_fax:
      - http://openid.net/schema/contact/phone/fax
    im_aim:
      - http://openid.net/schema/contact/IM/AIM
    im_icq:
      - http://openid.net/schema/contact/IM/ICQ
    im_msn:
      - http://openid.net/schema/contact/IM/MSN
    im_yahoo:
      - http://openid.net/schema/contact/IM/Yahoo
    im_jabber:
      - http://openid.net/schema/contact/IM/Jabber
    im_skype:
      - http://openid.net/schema/contact/IM/Skype
    image_default:
      - http://openid.net/schema/media/image/default
    biography:
      - http://openid.net/schema/media/biography
    web_default:
      - http://openid.net/schema/contact/web/default
    web_blog:
      - http://openid.net/schema/contact/web/blog
  trusted_domains:

development:
  <<: *default

test:
  <<: *default
  trusted_domains:
    - trusted-domain.com

production:
  <<: *default
  use_ssl: false
  ssl_certificate_common_name: your.domain.com
  ssl_certificate_sha1: D2:1B:D8:C4:39:B7:EE:10:DA:E2:4E:0A:65:98:8E:27:C9:32:4B:F0
  trusted_domains:
    - pc29-75.iu.hio.no
    - localhost